[package]
name = "fabricate"
version = "0.1.0"
authors = ["geometrically <jai.a@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.1.1"
handlebars = { version = "3.0.0", features = ["dir_source"] }
serde_json = "1.0"
serde = {version="1.0", features=["derive"]}
meilisearch-sdk = "0.1.3"
actix-files = "0.2.1"
diesel = { version = "1.4.4", features = ["postgres", "serde_json", "chrono"] }
dotenv = "0.9.0"
chrono = "0.4.11"
human_format = "1.0.3"
reqwest = "0.10.4"